name: build

on: [push, pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22, 24] # https://nodejs.org/en/about/releases/#releases

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm ci
        npm run build --if-present
        echo '{ "laxcomma": true }' > .jshintrc
        npm test
        npm run coverage
        npm run coveralls
      env:
        CI: true
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
